import {defineConfig} from "@anio-software/enkore"
import {defineTargetOptions} from "@anio-software/enkore.target-js-node"
import {
	generateFactoryWithInstantiationFile
} from "@anio-software/enkore.target-js-node/autogenerate"

export const config: unknown = defineConfig({
	target: {
		name: "js-node",
		options: defineTargetOptions({
			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			publish: [{
				registry: "anioSoftware"
			}]
		})
	},

	autogeneratedFiles: [
		...generateFactoryWithInstantiationFile({
			source: "project/src/__isDirectoryXXX.as.ts",
			destination: "project/export/__isDirectoryXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__isFileXXX.as.ts",
			destination: "project/export/__isFileXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__isRegularDirectoryXXX.as.ts",
			destination: "project/export/__isRegularDirectoryXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__isRegularFileXXX.as.ts",
			destination: "project/export/__isRegularFileXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__isSymbolicLinkXXX.as.ts",
			destination: "project/export/__isSymbolicLinkXXXFactory.as.ts"
		})
	]
})
